"""subsequent migration

Revision ID: 468c70d7f649
Revises: 5f4351649072
Create Date: 2023-07-01 22:12:33.516479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468c70d7f649'
down_revision = '5f4351649072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
