"""subsequent migration

Revision ID: 5f4351649072
Revises: dbd506ee1c5d
Create Date: 2023-07-01 22:01:19.604899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4351649072'
down_revision = 'dbd506ee1c5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
