"""subsequent migration

Revision ID: 898e49b6abda
Revises: 
Create Date: 2023-06-30 21:02:17.084459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898e49b6abda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
